### ISSUE TITLE
XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by wangxu94** [fabienli/DokuwikiAndroid#1]
Hi, first of all, thanks for working on this app. I've been looking for something like this for a long time.

I'm running the current build on Google Play (alpha1.17) on Android 7.0, and have enabled xmlrpc and whitelisted my user. I'm not able to see any of my pages on the app, and the log shows the error: `Failed to parse server's response: At line 1, column 4: XML or text declaration not at start of entity`.

I have attached screenshots of the start page, my settings, and the log page. Please let me know if it's a problem with my setup. Thanks!

![Screenshot_20190607-142832](https://user-images.githubusercontent.com/15028233/59078013-33626500-8931-11e9-9f66-363014a62ba0.png)

![2019-06-07_14-32-37](https://user-images.githubusercontent.com/15028233/59078003-26de0c80-8931-11e9-822a-6f3b9cdc0d2f.png)

![Screenshot_20190607-142838](https://user-images.githubusercontent.com/15028233/59078009-30677480-8931-11e9-935f-9a2e1d907707.png)

**Comment by fabienli** [comment]
Hello, 
thanks for your feedback, this will help make the app more mature.
As the application's logs complain about the format of the response received by the server, could you please do a basic check of the xmlrpc on your dokuwiki instance?

You can try the following curl commands to check the answers are ok (these are the two calls the android app is doing):

```
URLWIKI="https://<your server>/lib/exe/xmlrpc.php"
USERWIKI="<your user>"
PASSWORDWIKI="<your password>"

curl -b cookies -c cookies --header "Content-Type: application/xml" \
  --request POST \
  --data "<methodCall>
  <methodName>dokuwiki.login</methodName>
  <params>
  <param>
    <value>$USERWIKI</value>
  </param>
  <param>
    <value>$PASSWORDWIKI</value>
  </param>
  </params>
</methodCall>
" $URLWIKI

curl -b cookies -c cookies --header "Content-Type: application/xml" \
  --request POST \
  --data "<methodCall>
  <methodName>wiki.getPage</methodName>
  <params>
    <param>
      <value>start</value>
    </param>
  </params>
</methodCall>
" $URLWIKI
```

I'm interested to know if the answer is well starting by:
```
<?xml version="1.0"?>
<methodResponse>
(...)
```

**Comment by wangxu94** [comment]
Thanks for replying. The first curl command returns:

```
<?xml version="1.0"?>
<methodResponse>
  <params>
    <param>
      <value>
        <boolean>1</boolean>
      </value>
    </param>
  </params>
</methodResponse>
```

The second curl command returns:

```
<?xml version="1.0"?>
<methodResponse>
  <params>
    <param>
      <value>
        <string>======= Start page ========

[[wiki:help|Dokuwiki help]]\\
[[wiki:xls|xls2wiki]]\\
[[wiki:changes|Recent Changes]]

=== Weblog ===

&lt;tab&gt;[[personal:weblog|Private]]\\
&lt;tab&gt;[[wiki:weblog|Public]]

&lt;nspages -exclude:[sidebar sidebar_code start wiki] -h1 -actualTitle=6&gt;</string>
      </value>
    </param>
  </params>
</methodResponse>
```

Please let me know if you need anything else.

**Comment by fabienli** [comment]
Hi, I was expecting to spot some invalid xml, or unwanted space at the beginning, which doesn't read on your above results.
To find out the issue, I propose the following:
1. update your app to version alpha1.19 which enable to log the response
2. in settings > General: switch debug logs ON
3. go to start page (which should fail again)
4. display logs, as in your last screenshot
-> I expect to see more details, similar to the curl results, for example:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/2265539/59377338-4d95ac00-8d52-11e9-873e-116b7ec21bb8.png">
Could you please check this?

**Comment by wangxu94** [comment]
Here are the logs from the app:

```
page start loaded from local db
page start not in local db, get it from server
response:<?xml version="1.0"?>
response:<methodResponse>
response:  <params>
response:    <param>
response:      <value>
response:        <boolean>1</boolean>
response:      </value>
response:    </param>
response:  </params>
response:</methodResponse>
response:    <?xml version="1.0"?>
response:<methodResponse>
response:  <params>
response:    <param>
response:      <value>
response:        <string>
response:<h1 class=&quot;sectionedit1&quot; id=&quot;start_page&quot;>Start page</h1>
response:<div class=&quot;level1&quot;>
response:
response:<p>
response:<a href=&quot;/dokuwiki/doku.php?id=wiki:help&quot; class=&quot;wikilink1&quot; title=&quot;wiki:help&quot;>Dokuwiki help</a><br/>
response:
response:<a href=&quot;/dokuwiki/doku.php?id=wiki:xls&quot; class=&quot;wikilink1&quot; title=&quot;wiki:xls&quot;>xls2wiki</a><br/>
response:
response:<a href=&quot;/dokuwiki/doku.php?id=wiki:changes&quot; class=&quot;wikilink1&quot; title=&quot;wiki:changes&quot;>Recent Changes</a>
response:</p>
response:
response:</div>
response:
response:<h4 id=&quot;weblog&quot;>Weblog</h4>
response:<div class=&quot;level4&quot;>
response:
response:<p>
response:&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;<a href=&quot;/dokuwiki/doku.php?id=personal:weblog&quot; class=&quot;wikilink1&quot; title=&quot;personal:weblog&quot;>Private</a><br/>
response:
response:&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;<a href=&quot;/dokuwiki/doku.php?id=wiki:weblog&quot; class=&quot;wikilink1&quot; title=&quot;wiki:weblog&quot;>Public</a>
response:</p>
response:
response:<p>
response:<div class=&quot;plugin_nspages&quot;>
response:<h6 id=&quot;pages_in_this_namespace&quot;>Pages in this namespace:</h6>
response:
response:<div class=&quot;catpagecol&quot; style=&quot;width: 33.333333333333%&quot; ><div class=&quot;catpagechars&quot;>F</div>
response:<ul class=&quot;nspagesul&quot;>
response:<li class=&quot;level1&quot;><div class=&quot;li&quot;><a href=&quot;/dokuwiki/doku.php?id=family&quot; class=&quot;wikilink1&quot; title=&quot;family&quot;>Family</a></div>
response:</li>
response:</ul><div class=&quot;catpagechars&quot;>P</div>
response:<ul class=&quot;nspagesul&quot;>
response:<li class=&quot;level1&quot;><div class=&quot;li&quot;><a href=&quot;/dokuwiki/doku.php?id=personal&quot; class=&quot;wikilink1&quot; title=&quot;personal&quot;>Personal</a></div>
response:</li>
response:</ul></div>
response:
response:<div class=&quot;catpagecol&quot; style=&quot;width: 33.333333333333%&quot; ><div class=&quot;catpagechars&quot;>R</div>
response:<ul class=&quot;nspagesul&quot;>
response:<li class=&quot;level1&quot;><div class=&quot;li&quot;><a href=&quot;/dokuwiki/doku.php?id=recipes&quot; class=&quot;wikilink1&quot; title=&quot;recipes&quot;>Recipes</a></div>
response:</li>
response:</ul><div class=&quot;catpagechars&quot;>T</div>
response:<ul class=&quot;nspagesul&quot;>
response:<li class=&quot;level1&quot;><div class=&quot;li&quot;><a href=&quot;/dokuwiki/doku.php?id=travel&quot; class=&quot;wikilink1&quot; title=&quot;travel&quot;>Travel</a></div>
response:</li>
response:</ul></div>
response:
response:<div class=&quot;catpagecol&quot; style=&quot;width: 33.333333333333%&quot; ><div class=&quot;catpagechars&quot;>W</div>
response:<ul class=&quot;nspagesul&quot;>
response:<li class=&quot;level1&quot;><div class=&quot;li&quot;><a href=&quot;/dokuwiki/doku.php?id=work&quot; class=&quot;wikilink1&quot; title=&quot;work&quot;>Work</a></div>
response:</li>
response:</ul></div>
response:<div class=&quot;catpageeofidx&quot;></div></div>
response:</p>
response:
response:</div>
response:</string>
response:      </value>
response:    </param>
response:  </params>
response:</methodResponse>
XmlRpc decode wiki.getPageHTML response error: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: At line 1, column 4: XML or text declaration not at start of entity
```

For reference, this is what my start page looks like from my phone's web browser:
![image](https://user-images.githubusercontent.com/15028233/59381701-2d94d580-8db0-11e9-95dc-9f8735a0d65c.png)

**Comment by fabienli** [comment]
Ok, thanks for this information, the issue seems to come from this line:
```
response:    <?xml version="1.0"?>
```
you can spot some spaces before the "<", which is then causing the xml parser to fail.
This could be solved by checking on server side why those spaces are inserted, I'll also try to strip those spaces out in the app.
I'll let you know when a new version is ready to test again.

**Comment by wangxu94** [comment]
Thanks, that makes sense. I'll let you know too if I find a way to fix it on the server side.

P.S. a few more system details in case it's relevant, 
Dokuwiki version: Release 2018-04-22b "Greebo"
Webserver:  Apache/2.4.18 (Ubuntu)
OS: Ubuntu Server 16.04.6 LTS

**Comment by wangxu94** [comment]
Just an update, I've found the problem. I was using the [tab plugin](https://www.dokuwiki.org/plugin:tab) to put a tab before 2 lines on my start page. Removing the tab allowed the page to show up on the app.

However, there is now a new problem. When I click any of the links, the app crashes. I cannot see any logs because of the crash. I have also spun up a new dokuwiki for testing and I'm having the same problem there.

Would you like me to open a new issue for that?

Thanks again for all your work.

**Comment by fabienli** [comment]
OK, thanks for this feedback, I've opened a new issue [issue#2](https://github.com/fabienli/DokuwikiAndroid/issues/2) for this link issue.
