### ISSUE TITLE
crashing with nice url rewrite enabled

### ISSUE THREAD

**Issue by cwerner1** [fabienli/DokuwikiAndroid#10]
Hi

I've setup an dokuwiki on a subdomain.
My complete wiki url is https://wiki.xyz.com/
The app can open the initial start page (which is set in in the settings), but crashes if I want to open any other page.
for example in the start page the url is "/somepage", it will result in an Crash.

Greetings Christian

**Comment by fabienli** [comment]
Hi, the links are currently expected to follow the default format: https://wiki.xyz.com/doku.php?id=mypage.
I've not implemented the discovery of pages when URL are rewritten by "nice url".
Shouldn't be too difficult to adapt, keep in touch to test this soon here.

**Comment by fabienli** [comment]
fix proposed in: https://github.com/fabienli/DokuwikiAndroid/commit/a42cf8458bd8c66fc53a6d6d10b04ad17a0cc4a0

**Comment by cwerner1** [comment]
Thanks for your fast response
I tested it, but it doesnt work for my setup.

I added 2 Tests with my niceurl Setup in this Pull-Request.
https://github.com/fabienli/DokuwikiAndroid/pull/11

**Comment by fabienli** [comment]
ok, I made the doku.php part optional.
That passes your 2 tests.
Also, could you let me know how you're handling medias (if any)? are your URLs similar to:
/lib/exe/fetch.php/wiki:image.png

**Comment by cwerner1** [comment]
I've added a new picture in a page:
The namespace of the picture is "pasted", from the Copy&Paste Image Plugin

the dokuwiki syntax is:
`{{:pasted:20200522-225542.png}}`

the resulting rendered HTML is:

`<a href="/_detail/pasted:20200522-225542.png?id=start" class="media" title="pasted:20200522-225542.png"><img src="/_media/pasted:20200522-225542.png" class="media img-responsive" alt=""></a>`

**Comment by fabienli** [comment]
ok, I've added a commit that should handle the display of the image:
https://github.com/fabienli/DokuwikiAndroid/commit/42d14d0b32d62fbb3de15c5768fe90561f607e70
note that a click on an image that should display the "detail" page is not yet working

Let me know if that works for you. If ok, I'll publish the release tomorrow.

**Comment by cwerner1** [comment]
Works Fine
Pages are opening and also the images are shown.

Thank you for resolving this issue quickly!!
