### ISSUE TITLE
This app is dead ?

### ISSUE THREAD

**Issue by Gadgetroch** [fabienli/DokuwikiAndroid#107]
Hi,

I seek for a wiki and I want to be sure this app is not dead ?

Thanks for your response.

**Comment by fabienli** [comment]
Sure, the app is living !
This is just the Android app, the wiki is much more than this with the whole dokuwiki.org

**Comment by fabienli** [comment]
Contribution are also welcome!

**Comment by Gadgetroch** [comment]
Yeah I know, just I don't see update for 9 month want to be sure.

Thanks for responding me !
