### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [fabienli/DokuwikiAndroid#15]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by fabienli** [comment]
Screenshots added in https://github.com/fabienli/DokuwikiAndroid/tree/master/fastlane/metadata/android
Let's see in next releasing if that works fine !
