### ISSUE TITLE
Internal links crash

### ISSUE THREAD

**Issue by fabienli** [fabienli/DokuwikiAndroid#2]
"""
There is now a new problem. When I click any of the links, the app crashes. I cannot see any logs because of the crash. I have also spun up a new dokuwiki for testing and I'm having the same problem there.

Would you like me to open a new issue for that?

Thanks again for all your work.

EDIT: I've uploaded a recording showing the problem
https://gfycat.com/unrealisticcomfortableaffenpinscher
"""

**Comment by fabienli** [comment]
OK, I think there's an issue related to the server's folder where the wiki is installed (www.server.com/doku.php VS www.server.com/dokuwiki/doku.php) and how the internal link is then translated.
I've prepared a quick fix in release alpha1.20 (not handling media yet, just pages links), could you please confirm if this works better, so that I can then progress on that direction?

**Comment by wangxu94** [comment]
Yes the new release fixes the internal link problem.
