### ISSUE TITLE
Media not displayed

### ISSUE THREAD

**Issue by brenard** [fabienli/DokuwikiAndroid#24]
Media files (like png/jpg pictures) are not displayed on wiki pages or in media manager section. But, in media manager, on a picture for instance, if I click on "broken link picture", the picture is successfully opened on gallery app.

![Screenshot_20210421-003408](https://user-images.githubusercontent.com/421049/115472320-eee8c580-a239-11eb-8c43-c901445187aa.jpg)

Do you have any idea to solve that ?

**Comment by fabienli** [comment]
Hi @brenard ,
if you come for the second time on this page (after having displayed the image in gallery) is the image still broken?
Can you please let me know the model, and exact android version you're using, so that I can try to reproduce it ?

**Comment by brenard** [comment]
> Hi @brenard ,
> if you come for the second time on this page (after having displayed the image in gallery) is the image still broken?
> Can you please let me know the model, and exact android version you're using, so that I can try to reproduce it ?
Yes : I have a message saying that media have been downloaded and I can refresh the page, but when I leave the page and came back to it, the picture is still broken.

**Comment by fabienli** [comment]
fix ongoing

**Comment by brenard** [comment]
> fix ongoing

Great! Thanks!

**Comment by fabienli** [comment]
update fixing this issue is deployed on play store, should be soon available on fdroid also

**Comment by brenard** [comment]
> update fixing this issue is deployed on play store, should be soon available on fdroid also

Thanks ! I survey it and publish you a report (I'm using Fdroid).

**Comment by brenard** [comment]
> > update fixing this issue is deployed on play store, should be soon available on fdroid also
> 
> Thanks ! I survey it and publish you a report (I'm using Fdroid).

It's works like a charm! Thank you!
