### ISSUE TITLE
Support HTTP basic auth

### ISSUE THREAD

**Issue by michitux** [fabienli/DokuwikiAndroid#3]
As our wiki shall be completely private, I configured the web server to require HTTP basic auth. I configured DokuWiki with identical users/passwords and due to a nice but rather hidden feature in DokuWiki, you are then also automatically logged into DokuWiki. Depending on the web server, this actually also works if you haven't configured the web server to require HTTP auth, i.e., if you just send user and password via HTTP auth, the user is logged in.

So long story, short question: would it be possible to support just sending the same user and password configured for the wiki via HTTP auth if you get a 401 status, or just unconditionally, as this can replace the login call if the web server is configured correctly. Of course, this could also be a setting.

**Comment by fabienli** [comment]
ok, understood, I'm adding this as a new feature to the backlog.
Would you be ok to test this when a first version would be implemented?

**Comment by michitux** [comment]
Of course I can test this when a first version would be implemented, thank you very much for considering adding this feature.

**Comment by estribiyo** [comment]
I'm also interested in this feature...

**Comment by fabienli** [comment]
Hello there !
a new version has been delivered on Play store (should be shortly on f-droid as well).
You can now activate the "basic auth" authentication in the settings (Synchronisation tab).
Could you please confirm whether this works with your server's setup ?

I did some test with the following .htaccess file at the root of my wiki's folder:
```
AuthUserFile /home/user/www/dokuwiki/.htpasswd
AuthGroupFile /dev/null
AuthName "Restricted Access"
AuthType Basic
require valid-user
```

**Comment by michitux** [comment]
Yes, that works with my server's setup. I'm now seeing some other bugs, but I think they are unrelated. Thank you very much for implementing this!
