### ISSUE TITLE
App crashes without warning, no restart possible

### ISSUE THREAD

**Issue by vmario89** [fabienli/DokuwikiAndroid#39]
Hi,

after configuring our DokuWiki instance properly with XML-RPC, remoteuser and remote option, the app is going to crash as soon as i enter valid synchro settings. The app crashes and if i try to start it again it immediately closes always. i already removed cache and reconfigured, i also enabled debug logs... but i dont know where to find those files on my phone. so i have clearly no error message for you yet.

cheers, Mario

**Comment by fabienli** [comment]
Hi,
the debug log can be accessed in the left menu ... but if you can't open the app once it crashed, you won't see them.
Are you using the application from play store or from f-droid?
- if from play store, android might propose you to send a crash report, sending this report, I may identify something some bug there
- otherwise, you would need to get the log by plugging you phone to a computer and using the developers tools (adb).

maybe none of those 2 options are suitable to you, in that case maybe I could try to sync my own device to your server? (if you'd be ok to create a test user for me, we can get in contact privately to try and investigate further).

**Comment by vmario89** [comment]
hi,
for the environment i am working i may not share the connection for security reasons, but many thanks for the great offer! Id like to share info by adb. i already got the adb package for fedora. but how to log? do i need to use ./adb logcat? the connection to device worked fine (used https://www.xda-developers.com/install-adb-windows-macos-linux/#adbsetuplinux instructions)

**Comment by vmario89** [comment]
hey, i found out the app will not crash if i disable the extension https://www.dokuwiki.org/plugin:vshare - this seems to let crash DokuwikiAndroid

**Comment by fabienli** [comment]
Ok, I'll try to install this plugin to see if it happens to make the app crash for me as well

**Comment by fabienli** [comment]
reproduced the crash, by enabling vshare plugin and adding this into a page: "{{youtube>L-WM8YxwqEU}}"
I spotted the following error where the video link seems to be considered as a local media link; and then fails later on:

2022-01-24 10:54:15.679 29932-29932/com.fabienli.dokuwiki D/WebView: link to: file://www.youtube-nocookie.com/embed/L-WM8YxwqEU
2022-01-24 10:54:15.679 29932-29932/com.fabienli.dokuwiki D/WebView: link to: file://www.youtube-nocookie.com/embed/L-WM8YxwqEU
2022-01-24 10:54:15.679 29932-29932/com.fabienli.dokuwiki D/WebView: link to: www.youtube-nocookie.com
2022-01-24 10:54:15.679 29932-29932/com.fabienli.dokuwiki D/URL: file://www.youtube-nocookie.com/embed/L-WM8YxwqEU
2022-01-24 10:54:15.680 29932-29932/com.fabienli.dokuwiki A/bienli.dokuwik: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodV called with pending exception java.lang.IllegalArgumentException: Failed to find configured root that contains /www.youtube-nocookie.com/embed/L-WM8YxwqEU
    java_vm_ext.cc:577]   at android.net.Uri androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(java.io.File) (FileProvider.java:800)
    java_vm_ext.cc:577]   at android.net.Uri androidx.core.content.FileProvider.getUriForFile(android.content.Context, java.lang.String, java.io.File) (FileProvider.java:442)
    java_vm_ext.cc:577]   at boolean com.fabienli.dokuwiki.MainActivity$MyWebViewClient.shouldOverrideUrlLoading(android.webkit.WebView, java.lang.String) (MainActivity.java:380)
    java_vm_ext.cc:577]   at boolean android.webkit.WebViewClient.shouldOverrideUrlLoading(android.webkit.WebView, android.webkit.WebResourceRequest) (WebViewClient.java:83)
(...)

I'm trying to find a fix for this !

**Comment by vmario89** [comment]
many thanks @fabienli. i will reply back to your commit or in case i see anything else belonging to this thread. regards, Mario :)

**Comment by fabienli** [comment]
Fix for this issue is in commit: https://github.com/fabienli/DokuwikiAndroid/commit/48ce4a6566fd711bd9b194c1ad368252444ad596
Already deployed on play store, and should reach soon f-droid as well.

Let me know when you've been able to update your version if that solved your issue !

**Comment by vmario89** [comment]
Hi @fabienli. Thank you for fixing this issue. It works like a charm now. I am going to close it.

best regards, Mario
