### ISSUE TITLE
Download all pages with sync indicator

### ISSUE THREAD

**Issue by chappy721** [fabienli/DokuwikiAndroid#4]
Hi
first of all: thanks a lot for this great app!

Sync works fine, but I'm not sure, I think a page will only be stored locally after opening it on my Android (I tried with flightmode, and then I was not able to open every page).

For me it would be really great if my dokuwiki will be fully downloaded.

And here some download indicator would be nice.
Also in the current version I can sync but I do not really see if the app is still syncing or not.

BTW: can a donate? Do you have a paypal or so?:-)

Thanks!
Daniel

**Comment by fabienli** [comment]
Hi @chappy721 
thanks for using the app !

Sync is limited to a number of pages that can be changed in the Settings menu, maybe you should check that the limit is high enough for you? (also, there's a setting to choose between "only pages list" or "full sync", the second seems most fitted for you)

I'm updating the screen listing all the wiki's page (from left menu > "All Pages List") to let you know if a page needs to be synchronized. Let me know if that helps you.

When the sync is running, you should have a notification that let's you know:
  1 - that DokuwikiAndroid is running in the background
  2 - how is progressing the sync
is it showing on your device?

do not hesitate to provide further feedback on the app !

(no donation (yet?) in place, you can consider giving to dokuwiki's https://www.dokuwiki.org/donate  instead !)

Fabien

**Comment by chappy721** [comment]
Hi Fabien
thanks a lot! I didn't realize the options. Now the sync is working very well, also the full sync with media.
Thanks for your help.

Daniel
