### ISSUE TITLE
plugin catlist not working

### ISSUE THREAD

**Issue by chappy721** [fabienli/DokuwikiAndroid#5]
Hi again

just realized that catlist plugin does not show any pages in alpha 1.29.

Best wishes
Daniel

**Comment by fabienli** [comment]
Hi,
I'll check this, as this kind of plugin should be producing the html's content without impact on the app.

**Comment by fabienli** [comment]
This issue was fixed in catlist plugin (cf: https://github.com/xif-fr/dokuwiki-plugin-catlist/pull/32).
Could you please update catlist plugin in your dokuwiki's instance and let me know if you still have an issue?

**Comment by chappy721** [comment]
thankbyou!

Strange, Felix only updated syntax.php.
I replaced it bit now no rendering is made:
[cid:d02c2e83-0b70-44e7-829d-403d55faad58]

Sent from Nine<http://www.9folders.com/>
________________________________
Von: fabienli <notifications@github.com>
Gesendet: Freitag, 6. September 2019 15:19
An: fabienli/DokuwikiAndroid
Cc: Daniel Hofer; Author
Betreff: Re: [fabienli/DokuwikiAndroid] plugin catlist not working (#5)


This issue was fixed in catlist plugin (cf: xif-fr/dokuwiki-plugin-catlist#32<https://github.com/xif-fr/dokuwiki-plugin-catlist/pull/32>).
Could you please update catlist plugin in your dokuwiki's instance and let me know if you still have an issue?

**Comment by fabienli** [comment]
have you tried refreshing some dokuwiki's cache?
are you using some specific options that might have an impact to the rendering?

**Comment by chappy721** [comment]
I have no idea what I did;-), but...now it's working like a charm, thanks a lot!

**Comment by fabienli** [comment]
closing as fixed
