### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [fabienli/DokuwikiAndroid#50]
In the double screen rotation test to detect data loss, an application failure was identified: 

- EditActivity: Text disappears and popup menu disappears
- MainActivity: information disappears, night mode and normal mode, view property changes (changes from content_description': u'Close navigation drawer' to content_description': u'Open navigation drawer'), search disappears, view property changes (u' visible': True changes to u'visible': False), the text disappears, and returns to the previous page.

A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values. This issue is related to the activity's lifecycle (1). When a screen rotation occurs, the activity is destroyed and resumed. Data loss will happen if the developer does not save the variables before the destruction and restore them after creation. To avoid this, the developers have to implement both the logic necessary to save the activity state in the onSaveInstanceState() callback method and the logic to resume its state in the onRestoreInstanceState() callback method.
Another way to avoid data loss problems is to use the view model, designed to store and manage UI-related data in a lifecycle-conscious way (2).

- EditActivity: 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159801567-2f2e709c-3854-4e27-91c8-4a5ae1ab1e09.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159801565-2be8087c-52de-4390-a926-350e904a79e5.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159801663-b15f2c6d-43c0-4f78-aa8b-40994d40b207.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159801662-1558466d-d474-45e4-8bc7-4380fbcc99ff.png" width=20% height=20%>
</figure>

</div> 

- MainActivity: 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159801800-cfdf406a-7306-4379-91a5-238e3dde4a2f.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159801798-01323065-3c19-47b6-a7a5-380fe2fbcf9e.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159801872-6c8f0559-9109-4de7-b144-e34f46d38871.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159801868-5f6e0e13-b8e6-43c9-8569-fce674682895.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159802009-4e77305c-4c56-47c9-b004-bac0c077092f.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159802003-4766808d-1e35-4beb-9e19-d890f51a049c.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159802158-2d8a03b2-cc4b-41dc-8109-ea8dfdd1cdd1.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159802157-5334552b-1327-4375-97e3-b09f5f05cff6.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159802222-cde5eaf0-2ec7-436d-bc23-354ae9ad04e2.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159802219-61a4cd5a-fcd8-49a7-b969-ddee985510a3.png" width=20% height=20%>
</figure>

</div> 

Device:

- Device: Moto G30 with OS: Android 11
- Device language: English 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

1. https://developer.android.com/guide/components/activities/activity-lifecycle
2. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by fabienli** [comment]
fix ongoing in the Edit page:
https://github.com/fabienli/DokuwikiAndroid/commit/6a879f03281da63cb660068bcad2709700129a39

**Comment by fabienli** [comment]
testing with latest delivered version, this issue is now fixed
