### ISSUE TITLE
"add page" button

### ISSUE THREAD

**Issue by chappy721** [fabienli/DokuwikiAndroid#6]
For further development of DokuwikiAndroid I'd like to have a "add page" button. It is not necessary to be very complex. Just the possibility to create one simple page, perhaps in a predefined namespace, for example "inbox", would be really great.

Why I'd like to have this? Very often I make short notes on my android. I've used evernote so far and there it is very useful.

Another approach could be a markdown editor, but I was not able to find an editor with webdav connector. This could solve the lack of creating a new page.

Perhaps there is anybody who have ideas about that?
Thanks

**Comment by fabienli** [comment]
Hi, have you tried the "create page" option in the left menu?
I think that it's quite similar to what you are looking for:
- choose a page name
- select the namespace

currently the text you input will be the plain text, as you would enter when editing in dokuwiki's website. and the html rendering needs to be done by communicating with your dokuwiki's server. (no local preview yet, but that would be an interesting feature) 

tell me what you think about this !

**Comment by chappy721** [comment]
uups...I'm sorry! I didn't realize this option;-).
Yes that's exactly what I mean, perfect!

Thanks a lot!
