### ISSUE TITLE
Unable to connect on Android 9

### ISSUE THREAD

**Issue by tommy-mor** [fabienli/DokuwikiAndroid#7]
Error from in app log:
`XmlRpc call wiki.getPage error: org.apache.xmlrpc.XmlRpcException: Failed to read server's response: Cleartext HTTP traffic to 167.99.163.250 not permitted`

I think the solution may be pretty easy:
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

Cool project!

**Comment by fabienli** [comment]
version alpha1.31 should fix this.
Thanks to let me know if still a problem for you?

**Comment by tommy-mor** [comment]
Yep! Thanks for being so fast!
