### ISSUE TITLE
Crash when trying to sync

### ISSUE THREAD

**Issue by creinig** [fabienli/DokuwikiAndroid#8]
On my Galaxy S2, when selecting the "synchro" item from the main menu, the app always crashes to desktop.

Screenshot of the stacktrace:

![Screenshot_20190913-111732](https://user-images.githubusercontent.com/1583479/64851919-aa865400-d618-11e9-8f9a-dd8887292ac0.png)

Unfortunately that's all the crash report contained regarding the app itself.

Activating "full debug logs" doesn't give additional info as well.

**Comment by fabienli** [comment]
bug reproduced on my nexus S, I'll check what's happening there ...

**Comment by creinig** [comment]
Update : in the current version the app does not crash anymore. The "synchro" menu item doesn't give any feedback of what is happening, but the log contains a lot of responses from the sync operation.

**Comment by fabienli** [comment]
currently, there should be a notification when the sync is running. could you please confirm if this raised in your top bar ?

**Comment by creinig** [comment]
Confirmed. I just didn't notice it at first because (a) I expected some feedback in the app itself and (b) the sync (with nothing to do) went really quick.
